"""add profile_name to user table

Revision ID: 98b4745bb6a2
Revises: c9c256e5298a
Create Date: 2020-05-31 09:37:19.192077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b4745bb6a2'
down_revision = 'c9c256e5298a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_profile_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_profile_name', 'user', ['profile_name'], unique=False)
    # ### end Alembic commands ###
