"""add Profile Name

Revision ID: c9c256e5298a
Revises: cc54861c81fe
Create Date: 2020-05-30 17:32:47.250898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c256e5298a'
down_revision = 'cc54861c81fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_profile_name'), 'user', ['profile_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_name'), table_name='user')
    op.drop_column('user', 'profile_name')
    # ### end Alembic commands ###
